version: '3.5'
services:
  rsyslog:
      build: ./
      container_name: rsyslog
      restart: always
      privileged: true
  nginx-access-rsyslog:
      build: ./
      container_name: nginx-access-rsyslog
      command: ["/usr/sbin/rsyslogd", "-dn"]
      restart: always
      privileged: true
  nginx-error-rsyslog:
      build: ./
      container_name: nginx-error-rsyslog
      command: ["/usr/sbin/rsyslogd", "-dn"]
      restart: always
      privileged: true
networks:
  default:
    name: xgo-com